#!/usr/bin/env python3
"""Generate the manual Catalyst Data Store console provisioning checklist.

Reads docs/deployment/catalyst-schema-manifest.json (itself generated by
generate_schema_manifest.py) and produces
docs/deployment/catalyst-schema-console-checklist.md.

Why this exists as a script, not a hand-written doc: Catalyst Data Store has
no bulk-create and no schema-as-code import path for an existing project (see
docs/deployment/catalyst-schema.md) -- table/column creation is a manual
console action. This script is the only thing standing between "manual" and
"manual and error-prone": it applies the SQLite-to-Catalyst type mapping and
the primary-key/uniqueness adaptation consistently across all 351 columns, so
a reviewer only has to check the mapping rules once, here, rather than on
every row of a hand-typed checklist.

Regenerate whenever catalyst-schema-manifest.json changes.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "docs/deployment/catalyst-schema-manifest.json"
OUTPUT_PATH = REPO_ROOT / "docs/deployment/catalyst-schema-console-checklist.md"

# Columns already created by hand against the live KSP-CIP Development
# project during the first provisioning pass -- kept here so regenerating
# this checklist doesn't ask for them again. Extend this set as more columns
# are confirmed live.
ALREADY_DONE: set[tuple[str, str]] = {
    ("audit_event", "event_id"),
}


def build_plan(manifest: dict) -> tuple[list[str], dict[str, list[dict]], dict[str, list[str]]]:
    unique_targets: dict[str, set[str]] = defaultdict(set)
    for idx in manifest["indexes"]:
        if idx.get("unique") and len(idx["columns"]) == 1:
            unique_targets[idx["table"]].add(idx["columns"][0])

    order: list[str] = []
    by_table: dict[str, list[dict]] = defaultdict(list)
    composite_pk_tables: dict[str, list[str]] = {}

    type_map = {"TEXT": "Text", "INTEGER": "Bigint", "REAL": "Double"}

    for table in manifest["tables"]:
        name = table["table"]
        order.append(name)
        pk_cols = [c["name"] for c in table["columns"] if c["primary_key"]]
        composite = len(pk_cols) != 1
        if composite:
            composite_pk_tables[name] = pk_cols

        for col in table["columns"]:
            is_pk = col["primary_key"] and not composite
            is_unique_target = col["name"] in unique_targets.get(name, set())
            needs_unique = is_pk or is_unique_target

            if col["type"] == "TEXT":
                catalyst_type = "VarChar" if needs_unique else "Text"
            else:
                catalyst_type = type_map[col["type"]]

            by_table[name].append(
                {
                    "column": col["name"],
                    "catalyst_type": catalyst_type,
                    "max_length": 255 if catalyst_type == "VarChar" else None,
                    "is_mandatory": bool(col["not_null"] or col["primary_key"]),
                    "is_unique": needs_unique,
                }
            )

    return order, by_table, composite_pk_tables


def render(order: list[str], by_table: dict[str, list[dict]], composite_pk_tables: dict[str, list[str]]) -> str:
    lines: list[str] = []
    lines.append("# Catalyst Data Store — manual console provisioning checklist")
    lines.append("")
    lines.append("Generated by `scripts/generate_catalyst_console_checklist.py` from")
    lines.append("`docs/deployment/catalyst-schema-manifest.json`, for live, by-hand entry")
    lines.append("into the KSP-CIP Development project console (Cloud Scale -> Data")
    lines.append("Store). One table, one column at a time -- Catalyst has no bulk-create")
    lines.append("for either. Regenerate this file whenever the manifest changes; do not")
    lines.append("hand-edit it.")
    lines.append("")
    lines.append("## Read this first")
    lines.append("")
    lines.append(
        "- **Every new table already has 4 system columns**: `ROWID` (bigint,"
    )
    lines.append(
        "  the real storage primary key), `CREATORID` (bigint), `CREATEDTIME`"
    )
    lines.append(
        "  (datetime), `MODIFIEDTIME` (datetime). Do not recreate these -- only"
    )
    lines.append("  add the columns listed below per table.")
    lines.append(
        "- **Data Type dropdown** offers: Text, Var Char, Date, DateTime, Int,"
    )
    lines.append("  Double, Boolean, Bigint, Foreign Key, Encrypted Text.")
    lines.append("- **`Text` has no Is Unique / Search Index option** -- only Var Char and")
    lines.append("  the numeric types expose those toggles. That is why every column")
    lines.append("  needing uniqueness below is typed `Var Char`, not `Text`, even though")
    lines.append("  the source schema declares it `TEXT`.")
    lines.append("- **Var Char max length is capped at 255** by Catalyst itself. Every")
    lines.append("  `Var Char` row below uses 255.")
    lines.append("- **`Search Index` is Catalyst full-text search integration, not a query")
    lines.append("  index.** It is deliberately left off everywhere in this checklist --")
    lines.append("  turning it on does not give you the SQL-style index the original")
    lines.append("  schema declares.")
    lines.append("- **Composite primary keys cannot be enforced at the Data Store level.**")
    lines.append("  Catalyst's `Is Unique` constraint is single-column only. The tables")
    lines.append(
        "  below with more than one PK column (" + ", ".join(sorted(composite_pk_tables)) + ")"
    )
    lines.append("  get `Is Mandatory` on every key column and **no** `Is Unique` --")
    lines.append("  uniqueness across the combination is an application-level guarantee")
    lines.append("  only, same as the app already assumes for Catalyst per")
    lines.append("  `docs/deployment/catalyst-schema.md`.")
    lines.append("- **None of the 46 indexes in the manifest are creatable in Catalyst")
    lines.append("  Data Store.** There is no secondary/composite index feature for this")
    lines.append("  service (indexing exists only in Catalyst NoSQL, a different")
    lines.append("  service). This checklist does not attempt them -- see the note at the")
    lines.append("  end of this file for what to record instead.")
    lines.append("- One exception: `curated_CaseMaster.CrimeNo` is both a single-column")
    lines.append("  unique index (`ux_case_crimeno`) in the manifest and expressible in")
    lines.append("  Catalyst -- it is marked `Is Unique` below.")
    if ALREADY_DONE:
        done_desc = ", ".join(f"`{t}.{c}`" for t, c in sorted(ALREADY_DONE))
        lines.append(f"- Already created live: {done_desc}. Skip these if you reach them.")
    lines.append("")
    lines.append("## Per-table steps")
    lines.append("")
    lines.append(
        "For each table: **Data Store -> + New Table -> type the table name -> Create**,"
    )
    lines.append(
        "then for each column below: **+ New Column -> type Column Name -> pick Data"
    )
    lines.append(
        "Type -> (Var Char only) set Max Length to 255 -> toggle Is Mandatory / Is"
    )
    lines.append("Unique as marked -> Create**.")
    lines.append("")

    total_cols = 0
    for table in order:
        cols = by_table[table]
        remaining = [c for c in cols if (table, c["column"]) not in ALREADY_DONE]
        lines.append(f"### `{table}`  ({len(remaining)} columns)")
        if table in composite_pk_tables:
            lines.append(
                f'_Composite primary key: {", ".join(composite_pk_tables[table])} -- see note above._'
            )
        lines.append("")
        lines.append("| Column | Type | Max Len | Mandatory | Unique |")
        lines.append("|---|---|---|---|---|")
        for c in remaining:
            total_cols += 1
            lines.append(
                "| {} | {} | {} | {} | {} |".format(
                    c["column"],
                    c["catalyst_type"],
                    c["max_length"] or "-",
                    "Y" if c["is_mandatory"] else "-",
                    "Y" if c["is_unique"] else "-",
                )
            )
        lines.append("")

    lines.append("## What this checklist does not cover (record separately once done)")
    lines.append("")
    lines.append("- The 46 planned indexes cannot be created in Data Store. Update")
    lines.append("  `docs/deployment/catalyst-schema.md` to state this as verified (not")
    lines.append("  assumed) once this checklist is executed, and drop or rescope the")
    lines.append("  index-parity item in Phase D2 exit criteria.")
    lines.append("- Foreign keys are not enforced at the Data Store level anywhere in this")
    lines.append("  checklist (matches the manifest's own \"documentation of intent\" note).")
    lines.append("- `ctl_schema_version`, mentioned in `catalyst-schema.md` step 4, does not")
    lines.append("  exist in `schema.sql` or the manifest -- it was never implemented. Either")
    lines.append("  add it to the real schema first, or update that doc to drop the step.")
    lines.append("- PII/ePHI column tagging (a real Catalyst feature, distinct from the")
    lines.append("  source schema) was left off everywhere. Worth a follow-up pass over")
    lines.append("  person-identifying columns (names, addresses, phone numbers) once the")
    lines.append("  base schema is live.")
    lines.append("")

    print(f"tables: {len(order)}")
    print(f"columns listed (excluding already-done): {total_cols}")
    return "\n".join(lines) + "\n"


def main() -> None:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    order, by_table, composite_pk_tables = build_plan(manifest)
    text = render(order, by_table, composite_pk_tables)
    OUTPUT_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
